# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win007.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(744, 427)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 190, 721, 201))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 20, 61, 20))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 63, 54, 12))
        self.label_2.setObjectName("label_2")
        self.startcrawl = QtWidgets.QPushButton(self.centralwidget)
        self.startcrawl.setGeometry(QtCore.QRect(190, 95, 161, 31))
        self.startcrawl.setObjectName("startcrawl")
        self.crawlall = QtWidgets.QPushButton(self.centralwidget)
        self.crawlall.setGeometry(QtCore.QRect(10, 140, 151, 31))
        self.crawlall.setObjectName("crawlall")
        self.exit = QtWidgets.QPushButton(self.centralwidget)
        self.exit.setGeometry(QtCore.QRect(190, 140, 161, 31))
        self.exit.setObjectName("exit")
        self.rememberdata = QtWidgets.QCheckBox(self.centralwidget)
        self.rememberdata.setGeometry(QtCore.QRect(438, 143, 101, 21))
        self.rememberdata.setObjectName("rememberdata")
        self.sureupdate = QtWidgets.QPushButton(self.centralwidget)
        self.sureupdate.setGeometry(QtCore.QRect(572, 140, 151, 31))
        self.sureupdate.setObjectName("sureupdate")
        self.hostedit = QtWidgets.QLineEdit(self.centralwidget)
        self.hostedit.setGeometry(QtCore.QRect(450, 10, 141, 31))
        self.hostedit.setObjectName("hostedit")
        self.ipedit = QtWidgets.QLineEdit(self.centralwidget)
        self.ipedit.setGeometry(QtCore.QRect(670, 50, 61, 20))
        self.ipedit.setObjectName("ipedit")
        self.useredit = QtWidgets.QLineEdit(self.centralwidget)
        self.useredit.setGeometry(QtCore.QRect(450, 50, 141, 31))
        self.useredit.setObjectName("useredit")
        self.pwdedit = QtWidgets.QLineEdit(self.centralwidget)
        self.pwdedit.setGeometry(QtCore.QRect(450, 90, 141, 31))
        self.pwdedit.setObjectName("pwdedit")
        self.dbedit = QtWidgets.QLineEdit(self.centralwidget)
        self.dbedit.setGeometry(QtCore.QRect(670, 90, 61, 20))
        self.dbedit.setObjectName("dbedit")
        self.changedata = QtWidgets.QCheckBox(self.centralwidget)
        self.changedata.setGeometry(QtCore.QRect(630, 10, 91, 31))
        self.changedata.setObjectName("changedata")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(410, 20, 31, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(410, 60, 31, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(630, 50, 31, 20))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(610, 90, 61, 20))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(410, 100, 31, 16))
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(370, 10, 20, 161))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.starttime = QtWidgets.QLineEdit(self.centralwidget)
        self.starttime.setGeometry(QtCore.QRect(190, 10, 161, 31))
        self.starttime.setObjectName("starttime")
        self.endtime = QtWidgets.QLineEdit(self.centralwidget)
        self.endtime.setGeometry(QtCore.QRect(190, 53, 161, 31))
        self.endtime.setObjectName("endtime")
        self.checkBox_crawl = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_crawl.setGeometry(QtCore.QRect(20, 103, 131, 16))
        self.checkBox_crawl.setObjectName("checkBox_crawl")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 20, 71, 51))
        self.label_8.setObjectName("label_8")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 744, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "开始时间："))
        self.label_2.setText(_translate("MainWindow", "结束时间："))
        self.startcrawl.setText(_translate("MainWindow", "开始抓取自定义"))
        self.crawlall.setText(_translate("MainWindow", "一键获取历史数据"))
        self.exit.setText(_translate("MainWindow", "退出程序"))
        self.rememberdata.setText(_translate("MainWindow", "记住修改数据"))
        self.sureupdate.setText(_translate("MainWindow", "确认修改"))
        self.changedata.setText(_translate("MainWindow", "修改默认数据"))
        self.label_3.setText(_translate("MainWindow", "Host:"))
        self.label_4.setText(_translate("MainWindow", "User:"))
        self.label_5.setText(_translate("MainWindow", "Port:"))
        self.label_6.setText(_translate("MainWindow", "Database:"))
        self.label_7.setText(_translate("MainWindow", "Pwd:"))
        self.checkBox_crawl.setText(_translate("MainWindow", "自定义获取数据时间"))
        self.label_8.setText(_translate("MainWindow", "采集进度"))

