# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'win0168.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1345, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(2, 0, 1341, 601))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.search_result_team = QtWidgets.QTableView(self.tab)
        self.search_result_team.setGeometry(QtCore.QRect(0, 40, 631, 531))
        self.search_result_team.setObjectName("search_result_team")
        self.label_4 = QtWidgets.QLabel(self.tab)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 54, 12))
        self.label_4.setObjectName("label_4")
        self.search_time = QtWidgets.QLineEdit(self.tab)
        self.search_time.setGeometry(QtCore.QRect(59, 6, 113, 20))
        self.search_time.setObjectName("search_time")
        self.start_search = QtWidgets.QPushButton(self.tab)
        self.start_search.setGeometry(QtCore.QRect(180, 5, 101, 23))
        self.start_search.setObjectName("start_search")
        self.search_result_data = QtWidgets.QTableView(self.tab)
        self.search_result_data.setGeometry(QtCore.QRect(700, 60, 631, 511))
        self.search_result_data.setObjectName("search_result_data")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setGeometry(QtCore.QRect(686, 6, 16, 21))
        self.label_5.setObjectName("label_5")
        self.home_team = QtWidgets.QLabel(self.tab)
        self.home_team.setGeometry(QtCore.QRect(573, 8, 101, 21))
        self.home_team.setObjectName("home_team")
        self.away_team = QtWidgets.QLabel(self.tab)
        self.away_team.setGeometry(QtCore.QRect(723, 10, 91, 16))
        self.away_team.setObjectName("away_team")
        self.season = QtWidgets.QLabel(self.tab)
        self.season.setGeometry(QtCore.QRect(633, 33, 51, 20))
        self.season.setObjectName("season")
        self.game_time = QtWidgets.QLabel(self.tab)
        self.game_time.setGeometry(QtCore.QRect(694, 35, 121, 16))
        self.game_time.setObjectName("game_time")
        self.line_2 = QtWidgets.QFrame(self.tab)
        self.line_2.setGeometry(QtCore.QRect(820, 0, 3, 61))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab)
        self.line_3.setGeometry(QtCore.QRect(1081, 0, 20, 61))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.c_home = QtWidgets.QLabel(self.tab)
        self.c_home.setGeometry(QtCore.QRect(870, 0, 71, 16))
        self.c_home.setObjectName("c_home")
        self.c_hanld = QtWidgets.QLabel(self.tab)
        self.c_hanld.setGeometry(QtCore.QRect(940, 0, 71, 16))
        self.c_hanld.setObjectName("c_hanld")
        self.c_away = QtWidgets.QLabel(self.tab)
        self.c_away.setGeometry(QtCore.QRect(1010, 0, 71, 16))
        self.c_away.setObjectName("c_away")
        self.j_home = QtWidgets.QLabel(self.tab)
        self.j_home.setGeometry(QtCore.QRect(1100, 0, 71, 16))
        self.j_home.setObjectName("j_home")
        self.j_hanld = QtWidgets.QLabel(self.tab)
        self.j_hanld.setGeometry(QtCore.QRect(1170, 0, 71, 16))
        self.j_hanld.setObjectName("j_hanld")
        self.j_away = QtWidgets.QLabel(self.tab)
        self.j_away.setGeometry(QtCore.QRect(1240, 0, 71, 16))
        self.j_away.setObjectName("j_away")
        self.c_home_result = QtWidgets.QLabel(self.tab)
        self.c_home_result.setGeometry(QtCore.QRect(870, 15, 71, 16))
        self.c_home_result.setObjectName("c_home_result")
        self.c_hanld_result = QtWidgets.QLabel(self.tab)
        self.c_hanld_result.setGeometry(QtCore.QRect(940, 15, 71, 16))
        self.c_hanld_result.setObjectName("c_hanld_result")
        self.c_away_result = QtWidgets.QLabel(self.tab)
        self.c_away_result.setGeometry(QtCore.QRect(1010, 15, 71, 16))
        self.c_away_result.setObjectName("c_away_result")
        self.j_home_result = QtWidgets.QLabel(self.tab)
        self.j_home_result.setGeometry(QtCore.QRect(1100, 15, 71, 16))
        self.j_home_result.setObjectName("j_home_result")
        self.j_hanld_result = QtWidgets.QLabel(self.tab)
        self.j_hanld_result.setGeometry(QtCore.QRect(1170, 15, 71, 16))
        self.j_hanld_result.setObjectName("j_hanld_result")
        self.j_away_result = QtWidgets.QLabel(self.tab)
        self.j_away_result.setGeometry(QtCore.QRect(1240, 15, 71, 16))
        self.j_away_result.setObjectName("j_away_result")
        self.c_z = QtWidgets.QPushButton(self.tab)
        self.c_z.setGeometry(QtCore.QRect(640, 80, 51, 71))
        self.c_z.setObjectName("c_z")
        self.c_w = QtWidgets.QPushButton(self.tab)
        self.c_w.setGeometry(QtCore.QRect(640, 160, 51, 71))
        self.c_w.setObjectName("c_w")
        self.c_y = QtWidgets.QPushButton(self.tab)
        self.c_y.setGeometry(QtCore.QRect(640, 240, 51, 71))
        self.c_y.setObjectName("c_y")
        self.j_z = QtWidgets.QPushButton(self.tab)
        self.j_z.setGeometry(QtCore.QRect(640, 320, 51, 71))
        self.j_z.setObjectName("j_z")
        self.j_w = QtWidgets.QPushButton(self.tab)
        self.j_w.setGeometry(QtCore.QRect(640, 400, 51, 71))
        self.j_w.setObjectName("j_w")
        self.j_y = QtWidgets.QPushButton(self.tab)
        self.j_y.setGeometry(QtCore.QRect(640, 480, 51, 71))
        self.j_y.setObjectName("j_y")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setGeometry(QtCore.QRect(280, 0, 181, 41))
        self.label_6.setObjectName("label_6")
        self.j_hanld_result_2 = QtWidgets.QLabel(self.tab)
        self.j_hanld_result_2.setGeometry(QtCore.QRect(1170, 30, 71, 16))
        self.j_hanld_result_2.setObjectName("j_hanld_result_2")
        self.c_home_result_2 = QtWidgets.QLabel(self.tab)
        self.c_home_result_2.setGeometry(QtCore.QRect(870, 30, 71, 16))
        self.c_home_result_2.setObjectName("c_home_result_2")
        self.c_hanld_result_2 = QtWidgets.QLabel(self.tab)
        self.c_hanld_result_2.setGeometry(QtCore.QRect(940, 30, 71, 16))
        self.c_hanld_result_2.setObjectName("c_hanld_result_2")
        self.j_home_result_2 = QtWidgets.QLabel(self.tab)
        self.j_home_result_2.setGeometry(QtCore.QRect(1100, 30, 71, 16))
        self.j_home_result_2.setObjectName("j_home_result_2")
        self.c_away_result_2 = QtWidgets.QLabel(self.tab)
        self.c_away_result_2.setGeometry(QtCore.QRect(1010, 30, 71, 16))
        self.c_away_result_2.setObjectName("c_away_result_2")
        self.j_away_result_2 = QtWidgets.QLabel(self.tab)
        self.j_away_result_2.setGeometry(QtCore.QRect(1240, 30, 71, 16))
        self.j_away_result_2.setObjectName("j_away_result_2")
        self.j_hanld_result_3 = QtWidgets.QLabel(self.tab)
        self.j_hanld_result_3.setGeometry(QtCore.QRect(1170, 44, 71, 16))
        self.j_hanld_result_3.setObjectName("j_hanld_result_3")
        self.c_home_result_3 = QtWidgets.QLabel(self.tab)
        self.c_home_result_3.setGeometry(QtCore.QRect(870, 44, 71, 16))
        self.c_home_result_3.setObjectName("c_home_result_3")
        self.c_hanld_result_3 = QtWidgets.QLabel(self.tab)
        self.c_hanld_result_3.setGeometry(QtCore.QRect(940, 44, 71, 16))
        self.c_hanld_result_3.setObjectName("c_hanld_result_3")
        self.j_home_result_3 = QtWidgets.QLabel(self.tab)
        self.j_home_result_3.setGeometry(QtCore.QRect(1100, 44, 71, 16))
        self.j_home_result_3.setObjectName("j_home_result_3")
        self.c_away_result_3 = QtWidgets.QLabel(self.tab)
        self.c_away_result_3.setGeometry(QtCore.QRect(1010, 44, 71, 16))
        self.c_away_result_3.setObjectName("c_away_result_3")
        self.j_away_result_3 = QtWidgets.QLabel(self.tab)
        self.j_away_result_3.setGeometry(QtCore.QRect(1240, 44, 71, 16))
        self.j_away_result_3.setObjectName("j_away_result_3")
        self.c_home_2 = QtWidgets.QLabel(self.tab)
        self.c_home_2.setGeometry(QtCore.QRect(816, 16, 71, 16))
        self.c_home_2.setObjectName("c_home_2")
        self.c_home_3 = QtWidgets.QLabel(self.tab)
        self.c_home_3.setGeometry(QtCore.QRect(816, 31, 71, 16))
        self.c_home_3.setObjectName("c_home_3")
        self.c_home_4 = QtWidgets.QLabel(self.tab)
        self.c_home_4.setGeometry(QtCore.QRect(816, 45, 71, 16))
        self.c_home_4.setObjectName("c_home_4")
        self.home_team_2 = QtWidgets.QLabel(self.tab)
        self.home_team_2.setGeometry(QtCore.QRect(460, 5, 101, 31))
        self.home_team_2.setObjectName("home_team_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.start_spider_btn = QtWidgets.QPushButton(self.tab_2)
        self.start_spider_btn.setGeometry(QtCore.QRect(481, 57, 131, 31))
        font = QtGui.QFont()
        font.setFamily("新宋体")
        font.setBold(False)
        font.setWeight(50)
        self.start_spider_btn.setFont(font)
        self.start_spider_btn.setObjectName("start_spider_btn")
        self.spider_input_Edit = QtWidgets.QLineEdit(self.tab_2)
        self.spider_input_Edit.setGeometry(QtCore.QRect(280, 64, 113, 21))
        self.spider_input_Edit.setObjectName("spider_input_Edit")
        self.spiderEdit = QtWidgets.QTextEdit(self.tab_2)
        self.spiderEdit.setGeometry(QtCore.QRect(10, 90, 1321, 491))
        self.spiderEdit.setObjectName("spiderEdit")
        self.month_comboBox = QtWidgets.QComboBox(self.tab_2)
        self.month_comboBox.setGeometry(QtCore.QRect(403, 63, 69, 22))
        self.month_comboBox.setObjectName("month_comboBox")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.month_comboBox.addItem("")
        self.radioButton_by_month = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_by_month.setGeometry(QtCore.QRect(120, 68, 89, 16))
        self.radioButton_by_month.setObjectName("radioButton_by_month")
        self.radioButton_by_day = QtWidgets.QRadioButton(self.tab_2)
        self.radioButton_by_day.setGeometry(QtCore.QRect(200, 68, 89, 16))
        self.radioButton_by_day.setObjectName("radioButton_by_day")
        self.label = QtWidgets.QLabel(self.tab_2)
        self.label.setGeometry(QtCore.QRect(10, 66, 111, 21))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.tab_2)
        self.line.setGeometry(QtCore.QRect(0, 47, 1331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 54, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(30, 30, 981, 16))
        self.label_3.setObjectName("label_3")
        self.checkBox_include_new_data = QtWidgets.QCheckBox(self.tab_2)
        self.checkBox_include_new_data.setGeometry(QtCore.QRect(630, 65, 121, 16))
        self.checkBox_include_new_data.setObjectName("checkBox_include_new_data")
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1345, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "足球数据采集分析工具 version 1.0"))
        self.label_4.setText(_translate("MainWindow", "日期选择："))
        self.start_search.setText(_translate("MainWindow", "开    始"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-style:italic;\">vs</span></p></body></html>"))
        self.home_team.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-weight:600; color:#ff5500;\">主队</span></p></body></html>"))
        self.away_team.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-weight:600; color:#5555ff;\">客队</span></p></body></html>"))
        self.season.setText(_translate("MainWindow", "<html><head/><body><p align=\"right\"><span style=\" font-size:8pt;\">赛季</span></p></body></html>"))
        self.game_time.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">比赛时间</span></p></body></html>"))
        self.c_home.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">主胜</span></p></body></html>"))
        self.c_hanld.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">和局</span></p></body></html>"))
        self.c_away.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">客胜</span></p></body></html>"))
        self.j_home.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">主胜</span></p></body></html>"))
        self.j_hanld.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">和局</span></p></body></html>"))
        self.j_away.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">客胜</span></p></body></html>"))
        self.c_home_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_hanld_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_away_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_home_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_hanld_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_away_result.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_z.setText(_translate("MainWindow", "初始\n"
"总计"))
        self.c_w.setText(_translate("MainWindow", "初始\n"
"五大\n"
"联赛"))
        self.c_y.setText(_translate("MainWindow", "初始\n"
"比赛\n"
"数据"))
        self.j_z.setText(_translate("MainWindow", "即时\n"
"总计"))
        self.j_w.setText(_translate("MainWindow", "即时\n"
"五大\n"
"联赛"))
        self.j_y.setText(_translate("MainWindow", "即时\n"
"比赛\n"
"数据"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; color:#00aa00;\">正在查看的数据类型</span></p></body></html>"))
        self.j_hanld_result_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_home_result_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_hanld_result_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_home_result_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_away_result_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_away_result_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_hanld_result_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_home_result_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_hanld_result_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_home_result_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_away_result_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.j_away_result_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">0.00%</p></body></html>"))
        self.c_home_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">总计</span></p></body></html>"))
        self.c_home_3.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">五大联赛</span></p></body></html>"))
        self.c_home_4.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:8pt;\">比赛数据</span></p></body></html>"))
        self.home_team_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; color:#ff0000;\">公司总数：000</span></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "数据预览与统计"))
        self.start_spider_btn.setText(_translate("MainWindow", "开    始"))
        self.spider_input_Edit.setText(_translate("MainWindow", "2018-1-1"))
        self.month_comboBox.setItemText(0, _translate("MainWindow", "1"))
        self.month_comboBox.setItemText(1, _translate("MainWindow", "2"))
        self.month_comboBox.setItemText(2, _translate("MainWindow", "3"))
        self.month_comboBox.setItemText(3, _translate("MainWindow", "4"))
        self.month_comboBox.setItemText(4, _translate("MainWindow", "5"))
        self.month_comboBox.setItemText(5, _translate("MainWindow", "6"))
        self.month_comboBox.setItemText(6, _translate("MainWindow", "7"))
        self.month_comboBox.setItemText(7, _translate("MainWindow", "8"))
        self.month_comboBox.setItemText(8, _translate("MainWindow", "9"))
        self.month_comboBox.setItemText(9, _translate("MainWindow", "10"))
        self.month_comboBox.setItemText(10, _translate("MainWindow", "11"))
        self.month_comboBox.setItemText(11, _translate("MainWindow", "12"))
        self.radioButton_by_month.setText(_translate("MainWindow", "按月采集"))
        self.radioButton_by_day.setText(_translate("MainWindow", "按天采集"))
        self.label.setText(_translate("MainWindow", "数据采集方式选择"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">使用说明：</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:8pt;\">根据个人需求选择按月采集数据或者按照指定日期采集数据，例如：按月采集（输入年份2000，然后选择指定月份）、按天采集（输入指定日期2000-1-1）。点击开始，就可以在下方看见采集进度。</span></p></body></html>"))
        self.checkBox_include_new_data.setText(_translate("MainWindow", "是否包含实时数据"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "数据采集"))

